FROM python:stretch
# RUN apt-get update && apt-get install -y curl python3
# RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
# RUN python3 get-pip.py
RUN pip install mkdocs
WORKDIR /docs
